import { Component } from '@angular/core';

@Component({
  selector: 'app-card',
  templateUrl: './card.component.html',
  styleUrls: ['./card.component.css']
})
export class CardComponent {
 pdaList=[{"id":4268,"customerName":"RKSHIPS","berthName":"PTPTE","fileNo":"F/GOA/23-2314","jobNo":null,"portName":"PTTYYYYY","vesselTitle":"MT","vesselName":"BLUE RIBBON","eta":"10/05/2023","userName":"Rushikesh Sarode"},{"id":4267,"customerName":"CHEMIKALIEN SEETRANSPORT G.M.B.H.","berthName":"MARMAGAO","fileNo":"F/GOA/23-2313","jobNo":"OPA-TNTF05233528","portName":"KARWAR","vesselTitle":"MT","vesselName":"TALARA","eta":"08/05/2023","userName":"Shafay Khan"},{"id":4266,"customerName":"RKSHIPS","berthName":"PTPTE","fileNo":"F/GOA/23-2312","jobNo":"OPA-PTTYY05233526","portName":"PTTYYYYY","vesselTitle":"MT","vesselName":"BLUE RIBBON","eta":"05/05/2023","userName":"Rushikesh Sarode"},{"id":4265,"customerName":"ALPHA DYNAMICS OIL & GAS LTD","berthName":"BHARATHI DOCK 1\n","fileNo":"F/CHE/23-0042","jobNo":"T-INMAT05233527","portName":"CHENNAI","vesselTitle":"MT","vesselName":"AVANTI","eta":"03/05/2023","userName":"Avantika Naik"},{"id":4263,"customerName":"CAPITAL SHIP MANAGEMENT CORP","berthName":"HZR1","fileNo":"F/HAZ/23-0067","jobNo":"OPA-INHZ04233524","portName":"HAZIRA","vesselTitle":"MT","vesselName":"TALARA","eta":"19/04/2023","userName":"Shafay Khan"},{"id":4264,"customerName":"CHEM MIA SA","berthName":null,"fileNo":"F/BHA/23-0002","jobNo":"CB-BBNHJ04233525","portName":"BHAVNAGAR","vesselTitle":"MT","vesselName":"ABLE SAILOR","eta":"18/04/2023","userName":"James Bond"},{"id":4262,"customerName":"ADMIRAL MARINE CO SA","berthName":null,"fileNo":"F/JAM/23-0022","jobNo":null,"portName":"SIKKA GSFC","vesselTitle":"MT","vesselName":"ABALONE","eta":"18/04/2023","userName":"James Bond"},{"id":4261,"customerName":"WOMAR LOGISTICS PTE. LTD.","berthName":null,"fileNo":"F/HAZ/23-0066","jobNo":null,"portName":"HAZIRA","vesselTitle":"MT","vesselName":"ALPINE AMALIA","eta":"18/04/2023","userName":"Super Admin"},{"id":4260,"customerName":"WOMAR LOGISTICS PTE. LTD.","berthName":null,"fileNo":"F/HAZ/23-0065","jobNo":"CH-INHZ04233523","portName":"HAZIRA","vesselTitle":"MT","vesselName":"ALPINE AMALIA","eta":"15/04/2023","userName":"Super Admin"},{"id":4259,"customerName":" ALMI TANKERS S.A.","berthName":null,"fileNo":"F/GOA/23-2311","jobNo":"CBA-TNTF04233522","portName":"KARWAR","vesselTitle":"MT","vesselName":"B GAS SUMMIT","eta":"11/04/2023","userName":"James Bond"}]
}
